[package]
name = "blindroute-server"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "BlindRoute FHE HTTP gateway — serves encrypted compute via axum"
repository.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
blindroute-core.workspace = true
blindroute-ckks.workspace = true
blindroute-bfv.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
